kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc
provisioner: csi-cfsplugin
reclaimPolicy: Retain
parameters:
  cfsMaster1: 172.20.240.95:80
  cfsMaster2: 172.20.240.94:80
  cfsMaster3: 172.20.240.67:80
  volName: csi-dep
