kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cfs-csi-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: cfs-csi-node
  template:
    metadata:
      labels:
        app: cfs-csi-node
    spec: 
      serviceAccount: cfs-csi-service-account
      nodeSelector:
        csi.chubaofs.com/node: enabled
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.4.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.chubaofs.com/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.chubaofs.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
#            limits:
#              cpu: 500m
#              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins/csi.chubaofs.com
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - name: cfs-driver
          image: 10.196.31.173:5000/chubaofs/cfs-csi-driver:2.0.7
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/bin/bash", "/cfs/bin/start.sh"]
          env:
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/csi.chubaofs.com/csi.sock
            - name: DRIVER_NAME
              value: csi.chubaofs.com
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
#            limits:
#              cpu: 2000m
#              memory: 16Gi
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins/csi.chubaofs.com
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.chubaofs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: mountpoint-dir

