kind: Deployment
apiVersion: apps/v1
metadata:
  name: cfs-csi-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: cfs-csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cfs-csi-controller
    spec:
      serviceAccount: cfs-csi-service-account
      nodeSelector:
        csi.chubaofs.com/controller: enabled
      containers:
        - name: external-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.4.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --v=5
            - --provisioner=csi.chubaofs.com
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.chubaofs.com/csi.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          # limits:
          #   cpu: 500m
          #   memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins/csi.chubaofs.com
              name: socket-dir
        - name: external-attacher
          image: quay.io/k8scsi/csi-attacher:v0.4.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
#            limits:
#              cpu: 500m
#              memory: 512Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: cfs-driver
          image: 10.196.31.173:5000/chubaofs/cfs-csi-driver:2.0.7
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/bin/bash", "/cfs/bin/start.sh"]
          env:
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/csi.chubaofs.com/csi.sock
            - name: DRIVER_NAME
              value: csi.chubaofs.com
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
#            limits:
#              cpu: 500m
#              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins/csi.chubaofs.com
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.chubaofs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: mountpoint-dir

